bestofn_n: 4
bestofn_temperature: 0.2324214
bestofn_max_tokens: 4096
bestofn_rating_type: "absolute"  # or "pairwise"
planning_n: 2
planning_m: 2
planning_temperature_step1: 0.00055
planning_temperature_step2: 0.25
planning_temperature_step3: 0.999
planning_temperature_step4: 1.2
planning_max_tokens_step1: 96
planning_max_tokens_step2: 2
planning_max_tokens_step3: 8000
planning_max_tokens_step4: 0
